sources:
  - name: source
    database: '{{ target.catalog }}'  
    schema: source  
    tables:
      - name: dim_customer
      - name: dim_date
      - name: dim_product
      - name: dim_store
      - name: fact_returns
      - name: fact_sales
      - name: items
  - name: default
    database: '{{ target.catalog }}'  
    schema: default  
    tables:
      - name: lookup
  - name: default
    database: '{{ target.catalog }}'  
    schema: gold  
    tables:
      - name: source_gold_items

